FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

WORKDIR /app

# Copy only dependency files first for better caching
COPY pyproject.toml uv.lock ./

# Copy the rest of the application code
COPY apps/api ./apps/api

# Enable bytecode compilation 
ENV UV_COMPILE_BYTECODE=1

# Install dependencies
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --no-dev --frozen --package api

# Enable bytecode compilation and python optimizations 
ENV PYTHONOPTIMIZE=1
ENV PYTHONBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

# Set path to use the virtual environment's python
ENV PATH="/app/.venv/bin:$PATH"
ENV PYTHONPATH="/app/apps/api/src:$PYTHONPATH"

# Create a non-root user and set permissions
RUN addgroup --system app && \
    adduser --system --ingroup app app && \
    chown -R app:app /app

# Switch to the non-root user
USER app

# Expose the port that Streamlit will run on
EXPOSE 8000

WORKDIR /app/apps/api/src

# Set the entrypoint to run the Streamlit app
CMD ["uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]